name: Build APK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          cache: true

      - name: Régénérer la plateforme Android
        run: flutter create --platforms=android . --project-name gestion_betail

      - name: Vérifier la structure du projet
        run: |
          pwd
          ls -la
          find android -maxdepth 5 -name "AndroidManifest.xml" -print

      - name: Nettoyer le projet
        run: flutter clean

      - name: Installer les dépendances
        run: flutter pub get

      - name: Construire l'APK debug
        run: flutter build apk --debug

      - name: Construire l'APK release
        run: flutter build apk --release

      - name: Publier l'APK debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Publier l'APK release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk